### ISSUE TITLE
[Feature Request] Explain import codes to (new) posters

### ISSUE THREAD

**Issue by CactusPuppy** [Mitcheljager/workshop.codes#222]
# The problem
With the launch of Overwatch 2, many new users have stumbled upon Workshop.codes. These new users seem confused as to the function of Workshop.codes, and have created a number of posts (private, unlisted, and public) which have invalid import codes.

*Example invalid code from report*
![image](https://user-images.githubusercontent.com/10406383/205233610-5b578477-a5b5-4064-ac80-93b22e39b7ea.png)

# Potential solutions
- Provide a tooltip near the code field of the post form which links to [this wiki article](https://workshop.codes/wiki/articles/how-to-create-an-import-code-for-your-project) explaining how to generate valid import codes
- Attempt to detect codes which are "too human" and provide a popup
- Exclude draft and private codes from being included in the unique code check

**Comment by Mitcheljager** [comment]
This was fixed with https://github.com/Mitcheljager/workshop.codes/pull/239. At first I thought this may not have been enough, because who reads, but the number of bad posts has seriously decreased since this change.
