### ISSUE TITLE
[Editor] Auto indenting is often wrong

### ISSUE THREAD

**Issue by Mitcheljager** [Mitcheljager/workshop.codes#250]
When moving something to a new line using Enter the auto indenting is often wrong. I'm not sure of the exact cause or situation this happens in, but often times when trying to align each parameter in an action on it's own line will be auto indenting place it one intend too far.

It's a bit vague and not reliable to reproduce, but it happens often.

**Comment by CactusPuppy** [comment]
Probably fixed in #268
