### ISSUE TITLE
[Editor] Keywords are not syntax highlighted if the bracket is on the same line

### ISSUE THREAD

**Issue by Mitcheljager** [Mitcheljager/workshop.codes#291]
The first doesn't work, the second does.

```
actions { }

actions
{ }
```

![image](https://user-images.githubusercontent.com/12848235/232165158-23ad54d1-f692-482a-aa45-de42194eadc6.png)

**Comment by netux** [comment]
Works fine for me as of 41f39ddd018f5a720d0c7029ee1dcd61cc5b02e5

![image](https://github.com/Mitcheljager/workshop.codes/assets/6181929/664fd664-b73e-46b5-856d-ff87a537a696)
