### ISSUE TITLE
[Bug] "Copy to Clipboard" button on Snippet tab does not copy entire snippet

### ISSUE THREAD

**Issue by CactusPuppy** [Mitcheljager/workshop.codes#365]
![image](https://github.com/Mitcheljager/workshop.codes/assets/10406383/8985db37-bfe1-4580-b161-bee2a05982aa)
Clicking the "Copy to Clipboard" button is expected to copy the entire snippet, but it only copies what is currently loaded in the snippet viewer.

**Comment by Mitcheljager** [comment]
This is mostly true for very large snippets. If you wait a little bit it will copy the whole thing. It takes a second or 5 to render the whole snippet

**Comment by CactusPuppy** [comment]
> This is mostly true for very large snippets. If you wait a little bit it will copy the whole thing. It takes a second or 5 to render the whole snippet

Hm, is there any way we can detect when the full snippet is rendered and update/show the button once that occurs?

**Comment by Mitcheljager** [comment]
I think we might be able to feed it the full snippet instead. The main reason for the staggering is the syntax highlighting, the snippet doesn't need that

**Comment by Mitcheljager** [comment]
Fixed with 076be1389d95a88ebcae73da4ccdb9e0173680be
