### ISSUE TITLE
(Editor) Certain codes/gamemodes cause the editor to not save the project

### ISSUE THREAD

**Issue by mehAeon** [Mitcheljager/workshop.codes#470]
When I try to save the project with a problematic gamemode (for me it was the copy of settings of The Beast GV7E3) the editor refuses to save and bugs to always saying "Saving...". Other codes and gamemodes save fine

**Comment by Mitcheljager** [comment]
It seems to work perfectly fine for me. What browser and OS are you using?

**Comment by mehAeon** [comment]
firefox win11 23H2

**Comment by CactusPuppy** [comment]
Please try the following:
1. Open a new private window (`Ctrl + Shift + P`) so as to get rid of all your extensions, log into Workshop.codes, and try saving again.
2. Open a different browser (e.g. Microsoft Edge), and repeat trying to save your project.
3. If both of the above fail, please open your browser console using the key combination `Ctrl + Shift + I`, switch to the Console tab, and then try saving. If any errors appear after you try to save, please post the error here.

**Comment by CactusPuppy** [comment]
I've attempted to recreate this issue, and have been unable to repro. Closing until more information is provided.
